spring:
  datasource:
    url: jdbc:mysql://localhost:33060/gallery?useUnicode=true
    username: gallery0
    password: gallery
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
